let p = document.createElement("p");
let h3 = document.createElement("h3");
let div = document.createElement("div");
let h1 = document.createElement("h1");
let pp = document.createElement("p");
let body = document.querySelector("body");
p.innerText="Hey I'm red!";
p.style.color="red";
h3.innerText="Hey I'm blue!";
h3.style.color="blue";
h1.innerText="I'm in a div";
div.style.border="2px solid black";
div.style.backgroundColor="pink";
pp.innerText="ME TOO!";
body.append(p);
body.append(h3);
body.append(div);
div.insertAdjacentElement("afterbegin",h1);
div.append(pp);